import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Head from "next/head";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ahmed-Taha-CV",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 0.8,
  // You can add other properties here if needed, but be cautious with accessibility
  maximumScale: 1,
  userScalable: false, // Strongly discourage this for accessibility reasons
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=0.8, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <body
        style={{backgroundColor: "#F0F0F0"}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
